### ISSUE TITLE
Support embedded database

### ISSUE THREAD

**Issue by Roms1383** [Odonno/surrealdb-migrations#21]
Hi there and thanks for this lib it's super convenient to be able to run everything nicely in migrations.
Yesterday I gave a try at opening a PR to add support for embedded database (file/rocksdb/inflxdb) and came up with some result but I'm kinda stuck since the numerous tests are based on `surreal cli` which is not runnning in typical embedded context.
If you feel like it, maybe you can provide some guidance in implementing appropriate tests ?

**Comment by Odonno** [comment]
I am currently working on a Discord request to support migrations in a wasm context. I believe it will meet your needs to use migrations in an embedded database.

Regarding test implementation, I mainly (almost exclusively) write integration tests. And there are 2 folders to test either the cli or the library. As you said, the cli will be useless for an embedded context, so you'll need to modify the `lib.rs` and add tests in the `tests/library` folder.

Again, I am working on this, but would appreciate some feedback on the PR. I will share the PR when I'm ready.

**Comment by Odonno** [comment]
@Roms1383 You can take a look at the PR #23 

I made a sample app in a WASM context with a SurrealDB instance that uses IndexedDb storage. The sample app is pretty simple (almost stupid) but it works.

I am open to any suggestion and if that's ok for you, I'll merge the PR.
