### ISSUE TITLE
the default apply command also applies the .down.surql migration

### ISSUE THREAD

**Issue by happysalada** [Odonno/surrealdb-migrations#29]
trying to setup an initial database and adding a .down.surql, the initial apply command also applied it.
I'm going to try to put it in the down folder and see if that works better.

**Comment by Odonno** [comment]
Weird, are you using the v0.9.6?

It should work fine whether you have files in the `/down` folder or they finish with `.down.surql` in the `/migrations` folder

**Comment by happysalada** [comment]
I was using 0.9.5, I'm going to make the 0.9.6 update for nixpkgs in a couple of days.
Thanks a lot for the software!
My current project is setup, but I'll try again for the next project with the down suffix with version 0.9.6.

**Comment by Odonno** [comment]
If you are still using v0.9.5, you can put your DOWN files in the `/down` folder for the moment. They won't work but they will be applied, which is what you want. And when you will switch to v0.9.6, you will be able to apply these DOWN files.
