### ISSUE TITLE
Support Surreal<Client>

### ISSUE THREAD

**Issue by Keyruu** [Odonno/surrealdb-migrations#33]
I wanted to try out the library but I use the Surreal Client which isn't supported as it seems.
I just create a client like this:
```
let db = Surreal::new::<Ws>("127.0.0.1:8001")
        .await
        .expect("Failed to connect to server");
```
But the MigrationRunner expects a `&Surreal<surrealdb::engine::any::Any>`

This is the error I get:
```
mismatched types
expected reference `&Surreal<surrealdb::engine::any::Any>`
   found reference `&Surreal<Client>`
```

**Comment by Odonno** [comment]
Hi Lucas,

You're right. It was convenient to only use the `Any` engine but the lib should allow any type of engine/connection.

**Comment by Odonno** [comment]
This is now released in the v0.9.7

**Comment by Odonno** [comment]
@all-contributors please add @Keyruu for ideas

**Comment by Keyruu** [comment]
Thank you!
