### ISSUE TITLE
Improved error log with failed transactions

### ISSUE THREAD

**Issue by unidesigner** [Odonno/surrealdb-migrations#44]
When a migration fails with 
```
Error: The query was not executed due to a failed transaction

Caused by:
    The query was not executed due to a failed transaction
```
I'd like to see a more verbose error message what the reason was for the failed transaction. Would it be possible to display this information?

**Comment by Odonno** [comment]
Yes, I suppose we can go inside the surrealdb query response and extract the error message.

Great idea.

**Comment by unidesigner** [comment]
That would be fantastic!

**Comment by Odonno** [comment]
I have released the v1.0.1 crate which should now display the list of error messages when a migration fails.

**Comment by unidesigner** [comment]
I tried to compile v1.0.1. create with
`cargo install surrealdb-migrations@1.0.1`
but ran into a compile error 
```
error[E0658]: use of unstable library feature 'build_hasher_simple_hash_one'
    --> /home/stephan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ordered-multimap-0.7.1/src/list_ordered_multimap.rs:3288:34
     |
3288 |     let hash = self.build_hasher.hash_one(key);
     |                                  ^^^^^^^^
     |
     = note: see issue #86161 <https://github.com/rust-lang/rust/issues/86161> for more information


For more information about this error, try `rustc --explain E0658`.
error: could not compile `ordered-multimap` (lib) due to 27 previous errors
```

Any idea how to fix this?

**Comment by Odonno** [comment]
No problem on my end. What is your version of Rust? Can you try to upgrade to that latest version of Rust and see if the error disappear?

**Comment by unidesigner** [comment]
Updating Rust fixed the error. Thanks.
