### ISSUE TITLE
 missing field `executed_at`

### ISSUE THREAD

**Issue by jaymes15** [Odonno/surrealdb-migrations#46]
@Odonno While trying to apply migrations using `surrealdb-migrations apply` I get the following error:

```
Error: Failed to convert `[{ id: script_migration:0h0r8c71clh98jciohol, script_name: '20230717_225815_001_Index' }, { executed_at: '2023-07-17T21:56:38.217948925Z', id: script_migration:iwf5blj1nk7d5oj3pv8o, script_name: '20230717_225627_script_migration' }]` to `T`: missing field `executed_at`
```

Here is a screenshot for my migration folder:

<img width="334" alt="Screenshot 2023-07-17 at 23 15 21" src="https://github.com/Odonno/surrealdb-migrations/assets/46538679/bc321a29-42b7-4fde-bada-43589299d4f3">

I noticed from the error that `script_migration` as `executed_at` field in `20230717_225627_script_migration.surql` but
`20230717_225815_001_Index.surql` does not have `executed_at` field, hence the error.

<img width="935" alt="Screenshot 2023-07-17 at 23 17 10" src="https://github.com/Odonno/surrealdb-migrations/assets/46538679/1359cdd2-5b8c-4643-8899-540618d0486a">

<img width="770" alt="Screenshot 2023-07-18 at 05 27 44" src="https://github.com/Odonno/surrealdb-migrations/assets/46538679/b1c509b2-dc66-4e4c-a514-c771341c9eb6">

**Comment by Odonno** [comment]
I am curious. This should never happen. `script_migration` is an auto-managed table by this library, you should never modify the data or data structure.

If this is not reason of the problem, can you show the content of the `20230717_225627_script_migration.surql` file?

**Comment by jaymes15** [comment]
@Odonno here is the content of `script_migration.surql`

```
DEFINE TABLE script_migration SCHEMAFULL;

DEFINE FIELD script_name ON script_migration TYPE string;
DEFINE FIELD executed_at ON script_migration TYPE datetime VALUE $before OR time::now();

```
