### ISSUE TITLE
Unable to install surrealdb-migrations v0.9.12 on Mac

### ISSUE THREAD

**Issue by alveshelio** [Odonno/surrealdb-migrations#49]
**Describe the bug**
I'm unable to install surrealdb-migrtions V0.9.12 on Mac. I'm getting this error:

error: failed to compile `surrealdb-migrations v0.9.12`, intermediate artifacts can be found at `/var/folders/k5/5jb6fd397q533zjk9ql2d5pr0000gn/T/cargo-installMPq8Bd`

Caused by:
  failed to download replaced source registry `crates-io`

Caused by:
  failed to verify the checksum of `surrealdb v1.0.0-beta.9+20230402`

**To Reproduce**
I've just installed **cargo** version cargo 1.71.1 (7f1d04c00 2023-07-29) using **curl https://sh.rustup.rs -sSf | sh**
Then I've simply run command **cargo install surrealdb-migrations**
And I get the error above

**Expected behavior**
I'd expect **surrealdb-migrations** to install 

**Information**
- Mac version [Ventura 13.4.1]
- Mac chip [M1] 
- SurrealDB version: [1.0.0-beta.9+20230402.5eafebd for linux on aarch64]
- surrealdb-migration version: [0.9.12]

**Comment by Odonno** [comment]
This is related to a crates.io registry issue. See this issue here: https://github.com/surrealdb/surrealdb/issues/1850
Your only solution for the moment is to keep trying to install until it works. This will be fixed in beta-10.
