### ISSUE TITLE
Surrealdb-migrations compiled binary file

### ISSUE THREAD

**Issue by ansarizafar** [Odonno/surrealdb-migrations#6]
Surrealdb-migrations is an awesome project. It would be very convenient for  developers not using  Rust  to use this tool If a compiled binary file is provided.

**Comment by Odonno** [comment]
Hi Zafar,

This is great idea.

The compiled binaries are now integrated on every release. You can download the binaries from the latest release here: https://github.com/Odonno/surrealdb-migrations/releases/tag/v0.9.4
