### ISSUE TITLE
Running `cargo install surrealdb-migrations` currently fails

### ISSUE THREAD

**Issue by rcjara** [Odonno/surrealdb-migrations#61]
**Describe the bug**
Running cargo install surrealdb-migrations fails with the following output:

$ cargo install surrealdb-migrations
    Updating crates.io index
  Installing surrealdb-migrations v0.9.12
    Updating crates.io index
   Compiling proc-macro2 v1.0.69
   ... 
   Compiling surrealdb v1.0.0
   Compiling cli-table v0.4.7
   Compiling convert_case v0.6.0
   Compiling clap v4.4.8
   Compiling rust-ini v0.19.0
   Compiling diffy v0.3.0
   Compiling chrono-human-duration v0.1.1
   Compiling sqlparser v0.34.0
   Compiling fs_extra v1.3.0
   Compiling surrealdb-migrations v0.9.12
error[E0308]: mismatched types
  --> /Users/rjara/.cargo/registry/src/index.crates.io-6f17d22bba15001f/surrealdb-migrations-0.9.12/src/surrealdb.rs:66:5
   |
66 | /     client
67 | |         .signin(Root {
68 | |             username: &username,
69 | |             password: &password,
70 | |         })
71 | |         .await
   | |______________^ expected `Result<(), Error>`, found `Result<Jwt, Error>`
   |
   = note: expected enum `Result<(), _>`
              found enum `Result<Jwt, _>`

**To Reproduce**
Either: 
1) cargo install surrealdb-migrations --force

or 

1) clone this repo and navigate to the root directory
2) git checkout v0.9.12
3) rm Cargo.lock
4) cargo clean
5) cargo build

Please note step 3, which is definitely necessary to get the build to fail.

**Expected behavior**
cargo install surrealdb-migrations should not fail.

**Information**
- SurrealDB version: 1.0
- surrealdb-migration version: 0.9.12

**Additional context**
The Cargo.lock file currently checked in under v0.9.12 uses surrealdb version 1.0.0-beta.9+20230402.  On a clean install you get version 1.0.0 (without the beta.9+20230402).

**Comment by Odonno** [comment]
Hi Rhea,

I just published a new release. You should be able to download the v1.0.0 without error.

**Comment by rcjara** [comment]
Congrats on the release!
