### ISSUE TITLE
Unable to install surrealdb-migrations error[E0658]: use of unstable library feature 'stdsimd'

### ISSUE THREAD

**Issue by alveshelio** [Odonno/surrealdb-migrations#70]
**Describe the bug**
When I try to install surrealdb-migrations with `cargo install surrealdb-migrations` I get this error:
**error[E0658]: use of unstable library feature 'stdsimd'**

error[E0658]: use of unstable library feature 'stdsimd'
   --> ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ahash-0.8.7/src/operations.rs:124:24
    |
124 |     let res = unsafe { vaesmcq_u8(vaeseq_u8(transmute!(value), transmute!(0u128))) };
    |                        ^^^^^^^^^^
    |
    = note: see issue #48556 <https://github.com/rust-lang/rust/issues/48556> for more information

error[E0658]: use of unstable library feature 'stdsimd'
   --> ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ahash-0.8.7/src/operations.rs:124:35
    |
124 |     let res = unsafe { vaesmcq_u8(vaeseq_u8(transmute!(value), transmute!(0u128))) };
    |                                   ^^^^^^^^^
    |
    = note: see issue #48556 <https://github.com/rust-lang/rust/issues/48556> for more information

   Compiling quote v1.0.35
error[E0658]: use of unstable library feature 'stdsimd'
   --> ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ahash-0.8.7/src/operations.rs:154:24
    |
154 |     let res = unsafe { vaesimcq_u8(vaesdq_u8(transmute!(value), transmute!(0u128))) };
    |                        ^^^^^^^^^^^
    |
    = note: see issue #48556 <https://github.com/rust-lang/rust/issues/48556> for more information

error[E0658]: use of unstable library feature 'stdsimd'
   --> ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ahash-0.8.7/src/operations.rs:154:36
    |
154 |     let res = unsafe { vaesimcq_u8(vaesdq_u8(transmute!(value), transmute!(0u128))) };
    |                                    ^^^^^^^^^
    |
    = note: see issue #48556 <https://github.com/rust-lang/rust/issues/48556> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `ahash` (lib) due to 4 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `surrealdb-migrations v1.0.1`, intermediate artifacts can be found at `/var/folders/k5/5jb6fd397q533zjk9ql2d5pr0000gn/T/cargo-installa1UZKR`

**Information**
- SurrealDB version: **1.1.1 for macos on aarch64**
- surrealdb-migration version: **1.0.1**

**Comment by Odonno** [comment]
Hi @alveshelio 

I am sorry that this error happened. It will be hard for me to debug though. It might be related to macos, or could it be related to the Rust installed version?

Are you able to share the installed version of Rust on your machine?

**Comment by alveshelio** [comment]
Salut David,

Thank you for getting back.

I'm using `rustc 1.70.0 (90c541806 2023-05-31)` on Mac 14.2.1 (23C71). I hope this helps :)

**Comment by timlagrande** [comment]
The stdsimd feature got removed a few days ago.
You need to override your rust version to a previous version for your project until this changes, or roll back surrealdb migrations to a previous version.

**Comment by alveshelio** [comment]
@timlagrande Thank you for your help.

I was able to install surrealdb-migrations by upgrading rustc to version 1.76.0.
