### ISSUE TITLE
Crate documentation not build for 1.2.0

### ISSUE THREAD

**Issue by johansmitsnl** [Odonno/surrealdb-migrations#76]
**Describe the bug**
The crate documentation is not able to build.

**To Reproduce**
See https://docs.rs/crate/surrealdb-migrations/1.2.0/builds/1138412

**Expected behavior**
Documentation should be able to build

The commit that broke it is: 680152700bf9eee5080f83110e3403c51b09db12. Here you add the feature flag to the `.cargo/config.toml`.

You also need to enable this flag in order to build the project but it is not mentioned in the documentation.

**Comment by Odonno** [comment]
Hello Johan,

Good catch. Must add the `rustflags` to docs build too.

**Comment by Odonno** [comment]
Fixed in v1.2.2

Thank you again for creating this issue @johansmitsnl
