### ISSUE TITLE
Github Action to automatically execute migrations via CD

### ISSUE THREAD

**Issue by turulix** [Odonno/surrealdb-migrations#8]
it would be amazing to have an Github Action on the Marketplace for this, so you can easily deploy migrations via Github Actions for new releases.

**Comment by Odonno** [comment]
Oh, yes, I totally get that. You could go full Database GitOps.

I will try to see how to write a GitHub action project but I would like to put the project into this repository if possible.

If you want to do it, please let me know now.

**Comment by Odonno** [comment]
Looks like this is not a recommended practice to make a monorepo for this, per the doc: https://docs.github.com/en/actions/creating-actions/about-custom-actions#choosing-a-location-for-your-action

**Comment by Odonno** [comment]
Hi @turulix,

There is now a GitHub Action listed in the marketplace here: https://github.com/marketplace/actions/surrealdb-migrations

Please note that this is an early preview and new features will be added soon.
