### ISSUE TITLE
Does the library support surreal db v2?

### ISSUE THREAD

**Issue by RustLoverTheCoder** [Odonno/surrealdb-migrations#88]
Does the library support surreal db v2?
Because I have some features needed in v2 version

**Comment by Odonno** [comment]
Hello @RustLoverTheCoder, I suppose we should indeed move on to the 2.0 train. 

The v2.0.0-preview.1 is now released and should support surrealdb v2 alpha version. It is in preview until v2.0 is finally released.

Thank you for your patience.

**Comment by zvictor** [comment]
That works with Surrealdb [v2.0.0-alpha.10](https://github.com/surrealdb/surrealdb/releases/tag/v2.0.0-alpha.10), but not with [v2.0.0-beta.1](https://github.com/surrealdb/surrealdb/releases/tag/v2.0.0-beta.1) anymore.

When I run `surrealdb-migrations apply` against v2.0.0-beta.1 it does not produce any output and the process hangs forever.

**Comment by Odonno** [comment]
The surrealdb-migrations [v2.0.0-preview.2](https://github.com/Odonno/surrealdb-migrations/releases/tag/v2.0.0-preview.2) is now released. It will work with surrealdb v2.0.0-beta.1.

**Comment by zvictor** [comment]
`surrealdb-migrations:v2.0.0-preview.3` works for me with `surrealdb:v2.0.0-beta.2`, but when I try it with `surrealdb:v2.0.0` or `surrealdb:v2.0.1` it throws:

```haskell
Error:
   0: There was an error processing a remote HTTP request: HTTP status client error (400 Bad Request) for url (http://localhost:8000/rpc)
   1: There was an error processing a remote HTTP request: HTTP status client error (400 Bad Request) for url (http://localhost:8000/rpc)

Location:
   src/surrealdb.rs:108

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 3 frames hidden ⋮
   4: surrealdb_migrations::surrealdb::get_surrealdb_table_exists::{{closure}}::hed1e4b0b1b5cb5df
      at <unknown source file>:<unknown line>
   5: surrealdb_migrations::surrealdb::list_script_migration_ordered_by_execution_date::{{closure}}::h140686d672c8bd20
      at <unknown source file>:<unknown line>
   6: surrealdb_migrations::apply::main::{{closure}}::h25f1deb274ef1d96
      at <unknown source file>:<unknown line>
   7: surrealdb_migrations::sub_main::{{closure}}::hcd9ea589a98beae2
      at <unknown source file>:<unknown line>
   8: tokio::runtime::context::runtime::enter_runtime::ha36452590491261e
      at <unknown source file>:<unknown line>
   9: surrealdb_migrations::main::hdf18360032b5aa64
      at <unknown source file>:<unknown line>
  10: std::sys_common::backtrace::__rust_begin_short_backtrace::heb623f24ea2905d6
      at <unknown source file>:<unknown line>
  11: std::rt::lang_start::{{closure}}::hc6cc4f344098b525
      at <unknown source file>:<unknown line>
  12: std::panicking::try::h313170bb1d1d6e4b
      at <unknown source file>:<unknown line>
  13: std::rt::lang_start_internal::h6cc7d681663e7b4e
      at <unknown source file>:<unknown line>
  14: main<unknown>
      at <unknown source file>:<unknown line>
  15: __libc_start_call_main<unknown>
      at <unknown source file>:<unknown line>
  16: __libc_start_main@@GLIBC_2.34<unknown>
      at <unknown source file>:<unknown line>
  17: _start<unknown>
      at <unknown source file>:<unknown line>
      ```

**Comment by zvictor** [comment]
The problem remains the same for `surrealdb:v2.0.2`.

**Comment by Odonno** [comment]
Can you try with the WS protocol?

**Comment by zvictor** [comment]
With WS it works. Only HTTP that doesn't work in the versions I listed above.

**Comment by Odonno** [comment]
Do you use `http://localhost:8000/rpc` or `http://localhost:8000/`? I do remember that the correct address was simply `http://localhost:8000/`.
