### ISSUE TITLE
Question: Applying migrations fails during CI - file not found.

### ISSUE THREAD

**Issue by snarkipus** [Odonno/surrealdb-migrations#9]
## Question:
Is the `.surrealdb` configuration file required? 

## Issue:
As I was writing this, I realized I also had this issue when trying to invoke the CLI from an initialization script. For some reason, whether I have a configuration file specified or not, the test panics with the following during CI (Github actions):

[CI Panic](https://github.com/snarkipus/zero2axum/actions/runs/4866838355/jobs/8678777055#step:9:160):  'Failed to run migrations.: Path does not directory'

Note, this works when invoking `cargo test` but breaks when Github actions fires so I'm sure it's some sort of relative path thing, but I'm not entirely sure.

File: [tests/health_check.rs](https://github.com/snarkipus/zero2axum/blob/main/tests/health_check.rs)
```rust
pub async fn configure_database(config: SurrealdbConfiguration) -> color_eyre::Result<()> {
    SurrealdbMigrations::new(config)
        .up()
        .await
        .expect("Failed to run migrations.");

    Ok(())
}
```

## Repo:
- [zero2axum](https://github.com/snarkipus/zero2axum) - working through Zero to Production w/Axum & SurrealDB (or at least trying to)

**Comment by Odonno** [comment]
Hi @snarkipus 

The `.surrealdb` configuration file is not required unless you want to put your migration project inside a nested folder. In that case, specifiying the path is only possible with the configuration file. I can see you created your migration project at the root of your repository so you don't have to write a configuration. 

About the failure on the CI, can you make sure you are running the cli on the root folder? (where the Cargo.toml file is)

**Comment by Odonno** [comment]
I made a very simple repro project using the blog template and running integration test in the GitHub Actions CI. It works.

I will try to look into your code but right now, I do not see what can go wrong.

**Comment by Odonno** [comment]
The error `Path does not directory` is an error from the `fs_extra`. So clearly, there is something wrong with the filesystem. But the question is still why?

**Comment by Odonno** [comment]
Well, ok, it seems that the `events` folder does not exist because it is not created on the Git filesystem. Will make a fix asap.

**Comment by snarkipus** [comment]
Thanks @Odonno ! I'll report back if there's any more issues.
